spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agro_db
    username: agro
    password: agro
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
